### ISSUE TITLE
UTC is PC time rather than Game time

### ISSUE THREAD

**Issue by MattDiesel** [damencs/spawn-predictor#1]
If you're clock is slightly out on the computer, that causes the wrong wave to be predicted. Correct game UTC time can be seen in the clan panel for example. 

Not sure if there's anything you can actually do about this, I checked the code for the built in report button plugin and they're using the same built in java time tools. I can't see any plugin making use of the time from the clan panel.

**Comment by damencs** [comment]
This was updated in recent commits.
