### ISSUE TITLE
 Ability to Manually Set Rotation and Wave in FC Spawn Predictor Plugin

### ISSUE THREAD

**Issue by Benjames01** [damencs/spawn-predictor#3]
As a user of the FC Spawn Predictor plugin, I would like to request the ability to manually set the rotation and wave in case the plugin is started after entering the fight caves. Currently, the plugin automatically detects the rotation and wave upon entering the fight caves, but there are situations where this automatic detection may not be accurate or desirable.

Use Case:

Scenario: A user enters the fight caves without starting the FC Spawn Predictor plugin. After realizing the importance of using the plugin, they start it up, but the plugin is not aware of the current rotation and wave, leading to inaccurate predictions.

Desired Outcome: The user should be able to manually input the current rotation and wave to align the predictions with the actual state of the fight caves.
Scenario: A user accidentally resets the plugin while inside the fight caves due to a technical issue or an accidental key press. As a result, the plugin loses the information about the current rotation and wave.

Desired Outcome: The user should have the option to manually specify the rotation and wave again to continue using the plugin without interruption.
Expected Features:

Manual Input: Provide a user interface option to allow users to manually enter the rotation and wave information.
Validation: Implement validation checks to ensure that the entered rotation and wave values are within the correct range and correspond to valid configurations.
Persistence: Save the manually entered rotation and wave values, so they can be used until explicitly changed by the user or until the end of the fight caves session.
User Feedback: Provide clear and concise feedback to users when they enter the rotation and wave values to confirm that the values have been successfully updated.
Additional Information:

**Comment by damencs** [comment]
I could probably add this as a command within the chat, rather than a panel or config menu variant.

For example, ::sp setwave 34 and ::sp setrotation 2 - which would accomplish your request. I could then likely insert logic to provide these in the chat as an info snippet if someone starts the plugin mid raid and doesn't have a historical profile reference on it yet for the account (since I track those).

Do you think this would suffice?

**Comment by slowmobro** [comment]
I think the chat addition would be great. I just ran into an issue with the rotation provided by the plugin being wrong. I have identified which rotation I actually have and being able to now manually adjust it would be very useful, whether it be via a command or through the interface.

**Comment by Benjames01** [comment]
> I could probably add this as a command within the chat, rather than a panel or config menu variant.
> 
> For example, ::sp setwave 34 and ::sp setrotation 2 - which would accomplish your request. I could then likely insert logic to provide these in the chat as an info snippet if someone starts the plugin mid raid and doesn't have a historical profile reference on it yet for the account (since I track those).
> 
> Do you think this would suffice?

don't know if you've added this already, but yes that would be perfect

**Comment by pwatts6060** [comment]
Yeah +1. Also just had two runs where the plugin didn't display anything at all. Will post a separate issue too though.

**Comment by Benjames01** [comment]
> Yeah +1. Also just had two runs where the plugin didn't display anything at all. Will post a separate issue too though.

You probably did, but just in case, did you wait for it to calculate what the current rotation is before going in? Should say in the ui the current time and then after some time should say the rotation

**Comment by damencs** [comment]
This will be released in v1.2.0.
