### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pwatts6060** [damencs/spawn-predictor#6]
![image](https://github.com/damencs/spawn-predictor/assets/30028569/9c045f9f-bfea-45c9-97a7-998592328db1)

It was working earlier and I haven't changed any settings. In the last 2 runs it hasn't worked (I don't see the white/green tiles anywhere).
I can't just restart and re-enter since I'm on a slayer task that would get lost on leaving. 

This was on a leagues world if it matters.

**Comment by locosherman1** [comment]
Having this same issue, stopped working for whatever reason

**Comment by mrhappyasthma** [comment]
Doesn't work anymore for me either.

**Comment by damencs** [comment]
Config has been simplified and default has been set to "BOTH" for future users.
